### ISSUE TITLE
Install and Examples don't work

### ISSUE THREAD

**Issue by radiantone** [cfpb/regulations-parser#311]
Hi,
  Lots of great work here. Not sure it is still supported. I do get some odd install errors and  a runtime error trying to follow the example

± |master U:1 ?:2 ✗| → reg/bin/python build_from.py CFR-2012-title12-vol8-part1004.xml 12 2011-18676 15 1693
Traceback (most recent call last):
  File "build_from.py", line 20, in <module>
    from regparser.builder import (
  File "/home/radiant/regulations-parser/regparser/builder.py", line 11, in <module>
    from regparser import api_writer, content
  File "/home/radiant/regulations-parser/regparser/api_writer.py", line 18, in <module>
    from regparser.notice.encoder import AmendmentEncoder
  File "/home/radiant/regulations-parser/regparser/notice/encoder.py", line 3, in <module>
    from regparser.notice.diff import Amendment, DesignateAmendment
  File "/home/radiant/regulations-parser/regparser/notice/diff.py", line 8, in <module>
    from regparser.grammar import amdpar, tokens
  File "/home/radiant/regulations-parser/regparser/grammar/amdpar.py", line 9, in <module>
    from regparser.grammar import atomic, tokens, unified
  File "/home/radiant/regulations-parser/regparser/grammar/atomic.py", line 7, in <module>
    from regparser.grammar.utils import Marker, SuffixMarker, WordBoundaries
  File "/home/radiant/regulations-parser/regparser/grammar/utils.py", line 1, in <module>
    from pyparsing import alphanums, CaselessLiteral, getTokensEndLoc, Literal
ImportError: cannot import name getTokensEndLoc

**Comment by ascott1** [comment]
Hi @radiantone - I recommend taking a look at the [fork in the "eregs" organization](https://github.com/eregs/regulations-parser), which is under active development. I hope that helps!
